version: '2'
services:
    timesheet-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/timesheet/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=timesheet
            - POSTGRES_PASSWORD=
#        ports:
#            - 5432:5432
